#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
set script_name=`realpath $0 | xargs basename`
set log=$PWD/${script_name}.log
set diff_report=$log:h/${script_name}_diff_report.log
git rev-parse --show-toplevel >& /dev/null
if($status) then
    echo "\nERROR: Current directory is outside git directory tree\n"
    exit(1)
endif
set venv_path=$script_path:h:h/scripts/venv/smlp_package_venv
cd $venv_path/smlp
\rm -f regr_smlp/models/test{63,101}_model_y*_smlp_* >& /dev/null
\rm -rf regr_smlp/code/*{test,Test}* >& /dev/null
\rm -rf regr_smlp/code/{__pycache__,all_log.txt,logs.log,_doe.csv} >& /dev/null
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        exit(0)
    endif
endif
set prompt='%U%m%u:%B%~%b%#'
source ${venv_path}/bin/activate.csh
cd ${venv_path}/smlp/regr_smlp/code
echo "Log file: $log"
echo n | env CUDA_VISIBLE_DEVICES=-1 ./smlp_regr.py -w 8 -def n -t all -tol 7 -g |& tee $log
${script_path}/create_diff_report >& $diff_report
