# Use ubuntu 24.04 as an image
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Layer 1: base tools
RUN apt-get update && apt-get install -y \
    wget \
    vim \
    git \
    jq \
    tcsh \
    tzdata \
    locales \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*

# Layer 2: Python 3.11
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg \
        curl \
        ca-certificates && \
        curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF23C5A6CF475977595C89F51BA6932366A755776" \
            | gpg --dearmor -o /etc/apt/trusted.gpg.d/deadsnakes.gpg && \
        echo "deb https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble main" \
            > /etc/apt/sources.list.d/deadsnakes.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-dev \
        python3.11-tk \
        python3.11-distutils

# Layer 3: build tools
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    ninja-build \
    pkg-config \
    libgmp-dev \
    && rm -rf /var/lib/apt/lists/*

# Layer 4: Z3 and Boost
RUN apt-get update && apt-get install -y \
    python3-z3 \
    z3 \
    libz3-dev \
    libboost-python-dev \
    && rm -rf /var/lib/apt/lists/*

# Layer 5: X11 and GUI tools
RUN apt-get update && apt-get install -y \
    tk \
    tkcvs \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxi6 \
    x11-apps \
    x11-xserver-utils \
    x11vnc \
    xvfb \
    vim-gtk3 \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    autocutsel \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install pip
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

# Install Python packages including meson
RUN python3.11 -m pip install --ignore-installed --no-cache-dir -r requirements.txt

# Build python-boost
COPY run_python_boost_build .
RUN ./run_python_boost_build 11 && rm -rf /tmp/boost* /*/boost_py311

#Mathsat
COPY run_mathsat_build .
RUN ./run_mathsat_build && rm -rf /tmp/mathsat*

#Change python default version
RUN ln -sf /usr/bin/python3.11 /usr/bin/python3
RUN ln -sf /usr/bin/python3.11 /usr/bin/python

#tkdiff patch for https://bugs.launchpad.net/bugs/2139062
COPY run_tkdiff_patch .
RUN ./run_tkdiff_patch

# Copy the git clone script
COPY run_git_clone .
# Build SMLP
COPY run_meson_build .
ARG CACHE_BUST_SMLP
ARG GIT_BRANCH=master
RUN ./run_meson_build $GIT_BRANCH

#UTF-8 fonts
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

#Virtual display
COPY open_virtual_display .
#VNC
COPY start_vnc .

#SMLP link
RUN ln -sf /app/smlp/src/run_smlp.py /usr/local/bin/smlp

## Default command
CMD ["/bin/bash"]
