FROM ubuntu:22.04

# Avoid interactive prompts during apt install
ENV DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
RUN apt-get update && apt-get install -y \
        curl \
        git \
        jq \
        libgomp1 \
        locales \
        tcsh \
        tzdata \
        wget \
        vim \
        x11-xserver-utils \
        xvfb && \
    apt-get update && apt-get install -y \
        python3.11 python3.11-dev python3.11-distutils python3.11-venv python3.11-tk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------
# 2. Install pip and setuptools for Python 3.11
# ---------------------------------------------------------------------------
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    python3.11 -m pip install setuptools

# ---------------------------------------------------------------------------
# 3. mathsat
# ---------------------------------------------------------------------------
WORKDIR /app
COPY run_mathsat_build .
RUN ./run_mathsat_build && rm -rf /tmp/mathsat*

# ---------------------------------------------------------------------------
# 4. Clone smlp (ARG busts the cache to always get latest)
# ---------------------------------------------------------------------------
ARG CACHE_BUST_SMLP
ARG GIT_BRANCH=master
ARG RELEASE_TYPE
RUN echo "Building image for branch: $GIT_BRANCH"
COPY run_git_clone .
RUN cd /app && ./run_git_clone $GIT_BRANCH

# ---------------------------------------------------------------------------
# 5. Install smlp from wheel
# ---------------------------------------------------------------------------
COPY smlp_versions.py .
COPY run_pip_install  .
RUN ./run_pip_install $RELEASE_TYPE

# ---------------------------------------------------------------------------
# 6. Install UTF-8 fonts
# ---------------------------------------------------------------------------
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# ---------------------------------------------------------------------------
# 7. SMLP regression patch
# ---------------------------------------------------------------------------
COPY smlp_regr_patch .
RUN ./smlp_regr_patch

# ---------------------------------------------------------------------------
# 8. Define python version
# ---------------------------------------------------------------------------
RUN ln -sf /usr/bin/python3.11 /usr/bin/python
RUN ln -sf /usr/bin/python3.11 /usr/bin/python3

# ---------------------------------------------------------------------------
# 9. Copy and run DORA 
# ---------------------------------------------------------------------------
COPY run_dora /app
RUN ./run_dora

# ---------------------------------------------------------------------------
# 10. Copy script for opening virtual display - needed for regression
# ---------------------------------------------------------------------------
COPY open_virtual_display /app

# Default command
CMD ["/usr/bin/bash"]
