# Use ubuntu 24.04 as an image
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Layer 1: base tools
RUN apt-get update && apt-get install -y \
    wget \
    vim \
    git \
    jq \
    tcsh \
    tzdata \
    locales \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*

# Layer 2: Python 3.12
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3.12 \
        python3.12-tk \
        python-is-python3

# Layer 3: build tools
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    ninja-build \
    pkg-config \
    libgmp-dev \
    && rm -rf /var/lib/apt/lists/*

# Layer 4: Z3 and Boost
RUN apt-get update && apt-get install -y \
    python3-z3 \
    z3 \
    libz3-dev \
    libboost-python-dev \
    && rm -rf /var/lib/apt/lists/*

# Layer 5: X11 and GUI tools
RUN apt-get update && apt-get install -y \
    tk \
    tkcvs \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxi6 \
    x11-apps \
    x11-xserver-utils \
    x11vnc \
    xvfb \
    vim-gtk3 \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    autocutsel \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install Python packages including meson
RUN python -m pip install --ignore-installed --no-cache-dir -r requirements_312.txt --target /usr/local/lib/python3.12/dist-packages

#Mathsat
COPY run_mathsat_build .
RUN ./run_mathsat_build && rm -rf /tmp/mathsat*

#tkdiff patch for https://bugs.launchpad.net/bugs/2139062
COPY run_tkdiff_patch .
RUN ./run_tkdiff_patch

# Copy the git clone script
COPY run_git_clone .
# Build SMLP
COPY run_meson_build .
ARG CACHE_BUST_SMLP
ARG GIT_BRANCH=master
RUN ./run_meson_build $GIT_BRANCH

#UTF-8 fonts
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

#Virtual display
COPY open_virtual_display .
#VNC
COPY start_vnc .

#SMLP link
RUN ln -sf /app/smlp/src/run_smlp.py /usr/local/bin/smlp

## Default command
CMD ["/bin/bash"]
