#!/usr/bin/env bash
set -e  # Exit on error

# Get the directory where this script is located
build_dir="build"
output_dir="$HOME/.local_smlp"
kay_dir="$output_dir/kay"
smlp_dir="$output_dir/smlp"

# Clean up existing directories
rm -rf "/app/smlp/utils/poly/$build_dir" "$output_dir" 2>/dev/null || true

# Clone the kay repository
git clone https://github.com/fbrausse/kay "$kay_dir"

# Clone the smlp repository
#Build from branch, if remote branch exists
GIT_BRANCH=$1 
./run_git_clone $GIT_BRANCH

# Run meson setup
pip3.11 install meson
cd /app/smlp/utils/poly
python3.11 -m mesonbuild.mesonmain setup \
    --wipe \
    -Dkay-prefix="$kay_dir" \
    --prefix "$output_dir" "$build_dir"

/usr/bin/ninja -C build install
cp -rp $HOME/.local_smlp/lib/python3/dist-packages/smlp /usr/local/lib/python3.11/dist-packages
