#!/usr/bin/bash
script_name=$(realpath $0 | xargs basename)
log=$PWD/${script_name}.log
pref=Test83
\rm -f ${pref}* > /dev/null 2>&1
\rm -f $log logs.log > /dev/null 2>&1
if [[ $# -gt 0 ]]; then
    if [[ "$1" == "-clean" ]]; then
        exit 0
    fi
fi
package_path=$(ls -d /usr/local/lib*/python3.11/*-packages/smlp | head -1)
xvfb-run $package_path/run_smlp.py \
         -data smlp/regr_smlp/data/smlp_toy_num_resp_mult.csv \
         -out_dir ./ \
         -pref Test83 \
         -mode optimize \
         -pareto t \
         -opt_strategy lazy \
         -resp y1,y2 \
         -feat x,p1,p2 \
         -model dt_sklearn \
         -dt_sklearn_max_depth 15 \
         -tree_encoding nested \
         -compress_rules f \
         -spec smlp/regr_smlp/specs/smlp_toy_num_resp_mult_free_inps.spec \
         -data_scaler min_max -beta "y1>7 and y2>6" -objv_names obj1,objv2,objv3 -objv_exprs "(y1+y2)/2;y1/2-y2;y2" \
         -epsilon 0.05 \
         -delta_rel 0.01 \
         -save_model_config f \
         -mrmr_pred 0 \
         -plots f \
         -pred_plots f \
         -resp_plots f \
         -seed 10 \
         -log_time f |& tee $log
cmd="diff ${pref}_smlp_toy_num_resp_mult.txt smlp/regr_smlp/master"
echo $cmd && $cmd
