# SPDX-License-Identifier: Apache-2.0
# This file is part of smlp.


# ML constants
CLASSIFICATION = "classification"
REGRESSION = "regression"

# contingency and precision constants
FALSE_NEGATIVE = FN = BAD_OUT = 'FalNeg' # "PosOut"
TRUE_POSITIVE = TP = BAD_IN = 'TruPos'   # "PosIn
TRUE_NEGATIVE = TN = GOOD_OUT = 'TruNeg' # "NegOut"
FALSE_POSITIVE = FP = GOOD_IN = 'FalPos' # "NegIn"

# quality functions also referred to as quality targets and other hyper parameter defaults
PREDICTIVE_POSITIVE_VALUE = PPV = PRECISION = BAD_IN_VS_ALL_IN = 'Precision'    #"PosInVsAllIn"
TRUE_POSITIVE_RATE = SENSITIVITY = HIT_RATE = BAD_IN_VS_BAD_ALL = 'Sensitivity' #"PosdInVsPosAll"
NORM_POSITIVE_LIKELIHOOD_RATIO = NORM_POSITIVE_LR = NORM_BAD_LR = 'NormPosLR' # "NormPosLR"
BALANCED_PRECISION = BAD_IN_BALANCED = 'BalancedPrec'
WEIGHTED_RELATIVE_ACCURACY = WR_ACC = 'WRAcc'
LIFT = "Lift"
ENSEMBLE_ACC = 'EnsAcc'

# accuracy used both for classification and range analysis
ACCURACY = 'Accuracy'
COHEN_KAPPA = 'CohenKappa'
F1_SCORE = 'F1Score'
ROC_ACC = 'ROCAcc'

RANGE_ANALYSIS_PRECISIONS = [SENSITIVITY, PRECISION, BALANCED_PRECISION, LIFT,   
    NORM_POSITIVE_LR, WR_ACC, ROC_ACC, F1_SCORE, COHEN_KAPPA, ACCURACY, ENSEMBLE_ACC]
RANGE_ANALYSIS_FREQUENCES = [FALSE_NEGATIVE, TRUE_NEGATIVE, TRUE_POSITIVE, FALSE_POSITIVE]
RANGE_ANALYSIS_INDICATORS = RANGE_ANALYSIS_FREQUENCES + RANGE_ANALYSIS_PRECISIONS
        
#RANGE_ANALYSIS_PRECISIONS = [BAD_IN_VS_BAD_ALL, BAD_IN_VS_ALL_IN, BAD_IN_BALANCED, 
#    LIFT, NORM_BAD_LR, WR_ACC, ROC_ACC, F1_SCORE, COHEN_KAPPA, ACCURACY, ENSEMBLE_ACC]
#RANGE_ANALYSIS_FREQUENCES = [BAD_OUT, GOOD_OUT, BAD_IN, GOOD_IN]
#RANGE_ANALYSIS_INDICATORS = RANGE_ANALYSIS_FREQUENCES + RANGE_ANALYSIS_PRECISIONS

STAT_NEGATIVE_VALUE = int(0)
STAT_POSITIVE_VALUE = int(1)

# Range Constants
TP_SAMPLE_INDICES = 'TruePosSampleInd'
FP_SAMPLE_INDICES = 'FalsePosSampleInd'
FN_SAMPLE_INDICES = 'FalseNegSampleInd'
TN_SAMPLE_INDICES = 'TrueNegSampleInd'

