#!/usr/bin/env -S tcsh -f
set script_path=`realpath $0 | xargs dirname`
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        \rm -f dataset.txt.gz  >& /dev/null
        \rm -f Constraint_dora* *.log >& /dev/null
        exit(0)
    endif
endif
${script_path}/constraint_dora_dataset.py -timeout 5
set csv=Constraint_dora.csv
set json=`echo $csv:r | tr '[A-Z]' '[a-z]'`.json
gunzip -c dataset.txt.gz | tr ' ' , > $csv
smlp -data $csv \
    -spec $script_path/$json \
    -out_dir ./ \
    -pref $csv:r \
    -mode optimize \
    -pareto f \
    -opt_strategy eager \
    -resp Y1 \
    -feat X1,X2 \
    -model poly_sklearn \
    -tree_encoding flat \
    -compress_rules t \
    -mrmr_pred 0 \
    -epsilon 0.0000005 \
    -delta_rel 0 \
    -rad_rel 0 \
    -save_model t \
    -model_name $csv:r_model \
    -save_model_config t \
    -plots f \
    -pred_plots f \
    -resp_plots f \
    -seed 10 \
    -log_time f \
    >& `realpath $0 | xargs basename`.log
foreach var (X1 X2 Y1)
    echo $var = `jq ".objective1.${var}" Constraint_dora_Constraint_dora_optimization_results.json`
end
