#!/usr/bin/tcsh -f
set build_args=""
set image=smlp-manylinux_2_28-python312
\rm -f *.whl >& /dev/null
if($#argv > 0) then
    if("-rebuild_smlp" == "$argv[1]" ) then
        set build_args="--build-arg CACHE_BUST_SMLP=`date +%s`"
    else
        echo "\nUsage: `realpath $0 | xargs basename` [-rebuild_smlp]\n"
        exit 0
    endif
endif
set cmd="env DOCKER_BUILDKIT=1 docker build $build_args --progress=plain -t $image ."
echo $cmd
$cmd
if($status) then
    echo "\nERROR: Docker build faied\n"
    exit 1
else
    docker create --name smlp_tmp $image
    docker cp smlp_tmp:/app/smlp/dist/. /tmp/smlp_dist_tmp
    docker rm smlp_tmp
    mv /tmp/smlp_dist_tmp/smlptech-*manylinux*.whl .
    rm -rf /tmp/smlp_dist_tmp
endif
if(-s *.whl ) then
    echo "\nWheel: `realpath *.whl`\n"
    exit 0
else
    echo "\nERROR: failed to copy wheel to host\n"
    exit 1
endif
