#!/usr/bin/tcsh -f
set build_args=""
set image=smlp-manylinux_2_28-python312
\rm -f *.whl >& /dev/null
env DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t $image .
if($status) then
    echo "\nERROR: Docker build faied\n"
    exit 1
else
    docker create --name smlp_tmp $image
    docker cp smlp_tmp:/app/smlp/dist/. /tmp/smlp_dist_tmp
    docker rm smlp_tmp
    mv /tmp/smlp_dist_tmp/smlptech-*manylinux*.whl .
    rm -rf /tmp/smlp_dist_tmp
endif
if(-s *.whl ) then
    echo "\nWheel: `realpath *.whl`\n"
    exit 0
else
    echo "\nERROR: failed to copy wheel to host\n"
    exit 1
endif
